### ISSUE TITLE
I got segmentation  fault when I run rpm  baidunetdisk

### ISSUE THREAD

**Issue by eladawy1988** [flathub/com.baidu.NetDisk#46]
I got the following log error 

/opt/baidunetdisk/baidunetdisk --no-sandbox %U
tempArray[0]: grep -i baidu /usr/share/applications/*.desktop 
ndevice name: virbr0
browser engine version: 1.0.4.32
(node:22477) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
Segmentation fault (core dumped)

any help ???

**Comment by hexchain** [comment]
Should be fixed with #45.
